### ISSUE TITLE
FD-002.2 Create Mission 🏠

### ISSUE THREAD

**Issue by lanicemp** [Young-N-Ambitious/yna_frontend#10]
**Description:**

- Create a component displaying the YNA mission statement.

**Acceptance** Criteria:

- Title: Mission

- Mission Description

**Figma:**

- https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?node-id=156%3A12

**Comment by KiloWattDot** [comment]
Working on this.

**Comment by DCTorres1987** [comment]
@lanicemp can you please assign issue to me?

**Comment by Sydnee510** [comment]
Hello @DCTorres1987 can you update your PR so it can get merged in. Thanks :)
