### ISSUE TITLE
FD-002.3 Create Featured Members Component 🏠

### ISSUE THREAD

**Issue by lanicemp** [Young-N-Ambitious/yna_frontend#11]
**Description:**

- Create the featured members component

Acceptance Criteria:

- Import / create Member cards

- include test for this component 

**Figma:**

- https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?node-id=156%3A12

**Comment by Clue355** [comment]
what's the status of this @marlovigor

**Comment by Sydnee510** [comment]
This issue can now be addressed.

The members will get imported from the API once it is up and running. For now, create the component and start the styling of the component. Use the figma as a reference.
