### ISSUE TITLE
FD-005.1 Create Member Page Header Nav 

### ISSUE THREAD

**Issue by Clue355** [Young-N-Ambitious/yna_frontend#110]
**Description:**
- Create a header with filtered navigation tabs by 3 top job titles/professions 
- This should be built directly into the member head component
- be sure the search bar is imported here as well

**Job titles/professions:**
- Software Engineer
- Project Manager
- Security 

**Acceptance Criteria:**
- Title: Explore our Members!
- Header: filter by job title/profession
- Import Search Bar

**Comment by cworthen** [comment]
Hello, I would like to work on this ticket.
