### ISSUE TITLE
FD-005.3 Member card component

### ISSUE THREAD

**Issue by Clue355** [Young-N-Ambitious/yna_frontend#112]
Description:
Create a reusable Member Card component with a name, job field, portfolio link, & social media links Once you create the component... import the member card component into the head member component (screenshot of the head member component below)

![Screenshot 2023-08-31 at 2 02 45 PM](https://github.com/Young-N-Ambitious/yna_frontend/assets/16109830/58cbaf65-5960-4890-bc43-3e3570f59712)

Acceptance Criteria:
- Card Component
- This may change. We want to make one general member card to be used throughout the website. (reusable component)

Figma: 
https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?type=design&node-id=156%3A12&mode=design&t=SKyRV53gH1aXn7Zz-1

**Comment by vazquezea96** [comment]
I would like to tackle this

**Comment by ZeeMonk-pixel** [comment]
Hi, I can work on this, if you will assign this issue to me.

**Comment by Sydnee510** [comment]
hey @ZeeMonk-pixel do you still want to tackle this?

**Comment by ZeeMonk-pixel** [comment]
Yeah I'll love to... I'll need to see what the card design looks like though

**Comment by Sydnee510** [comment]
hey @ZeeMonk-pixel I have attached the figma resource above

**Comment by ZeeMonk-pixel** [comment]
okay. thanks @Sydnee510 . I'll get to work on it

**Comment by cworthen** [comment]
Hey, wanted to mention that since the member page has a header and styling that needs to be added, I'll add the base styling in this [ticket](https://github.com/Young-N-Ambitious/yna_frontend/issues/111).
