### ISSUE TITLE
Members desktop page

### ISSUE THREAD

**Issue by cworthen** [Young-N-Ambitious/yna_frontend#120]
Description:

Create Members desktop page that lists all members, please see screenshot below. 
![Screenshot 2023-08-31 at 2 02 45 PM](https://github.com/Young-N-Ambitious/yna_frontend/assets/16109830/58cbaf65-5960-4890-bc43-3e3570f59712)

**Comment by Sydnee510** [comment]
This issue will be address here: https://github.com/Young-N-Ambitious/yna_frontend/issues/112
