### ISSUE TITLE
FD-003.2 Create Global Footer 🌎

### ISSUE THREAD

**Issue by brianpompey** [Young-N-Ambitious/yna_frontend#23]
Description:

     - Create the Footer with the appropriate links

Acceptance Criteria:

     - include link to YNA TWITTER https://twitter.com/YNA_Squad
     - include link to YNA Linkedin  https://www.linkedin.com/company/yna-consult-group/
     - create and include testing file

**Comment by trybick** [comment]
If you need someone for this, I can do it
