### ISSUE TITLE
FD-003.1.2 Create Global Nav Bar 🌎

### ISSUE THREAD

**Issue by lanicemp** [Young-N-Ambitious/yna_frontend#32]
Description:

Create the Navbar with the appropriate tabs and YNA logo.
Acceptance Criteria:

 Tabs:

Home | About | Members | Contact | Join

All links should redirect to the appropriate pages.

Add testing component to check for functionality.

Figma:

https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?node-id=156%3A12

**Comment by Clue355** [comment]
@KiloWattDot what's the status on this?

**Comment by Sydnee510** [comment]
@Clue355 will begin working on this issue
