### ISSUE TITLE
FD-002.2 Create Mission Statement

### ISSUE THREAD

**Issue by DCTorres1987** [Young-N-Ambitious/yna_frontend#34]
Assigning issue to myself.

**Comment by Clue355** [comment]
did you complete this @DCTorres1987

**Comment by Clue355** [comment]
I don't understand what this issue is about. If it's for the mission component that has been completed @Sydnee510

**Comment by DCTorres1987** [comment]
@Clue355 I'm currently working on this issue. I had to wait until my pr was merged.

**Comment by Sydnee510** [comment]
This is an issue that needs to be adressed

Description:
Create a component displaying the YNA mission statement.
Acceptance Criteria:
Title: Mission
Mission Description

**Comment by Clue355** [comment]
already completed link here: https://github.com/Young-N-Ambitious/yna_frontend/tree/dev/src/pages/mission
