### ISSUE TITLE
FD-001.2 Create Environment Setup Instructions

### ISSUE THREAD

**Issue by Sydnee510** [Young-N-Ambitious/yna_frontend#35]
create a markdown file with the environment setup instructions for a mac and link that file in the initial readme.

**Comment by Clue355** [comment]
does the current file instrustions work for mac??

**Comment by Sydnee510** [comment]
we have current mac setup instructions on the backend repository. check it out here: https://github.com/Young-N-Ambitious/yna_backend/blob/main/EnvironmentSetup.md

**Comment by Sydnee510** [comment]
This is a small issue still needing to be addressed. We should have a simple environment setup markdown file for users to get their environment set up for running a react application.

**Comment by bball07** [comment]
I can take this issue
