### ISSUE TITLE
FD-0001 Clean Up Readme

### ISSUE THREAD

**Issue by Sydnee510** [Young-N-Ambitious/yna_frontend#36]
The frontend readme has a few syntax errors and repetition. We want the readme to look as clean as possible.
Update it to match the backend readme. Example here: https://github.com/Young-N-Ambitious/yna_backend

**Comment by Sydnee510** [comment]
we still need this issue addressed. @brianpompey you want to take it on?

**Comment by SincerelyBrittany** [comment]
Do you need help with this? @Sydnee510

**Comment by Sydnee510** [comment]
this issue is a pretty small fix... there are currently some repetitious statements regarding contributing to the project in the last few lines... Developer can make changes to the end of the readme by just telling the user to "Join the YNA community" and including the application link. use the backend readme as a reference https://github.com/Young-N-Ambitious/yna_backend

**Comment by bball07** [comment]
I'll take this issue
