### ISSUE TITLE
FD - 002.5 - Make Header Responsive

### ISSUE THREAD

**Issue by SincerelyBrittany** [Young-N-Ambitious/yna_frontend#47]

**Comment by Sydnee510** [comment]
Here goes the updated mockups for the hamburger menu:
![Screen Shot 2023-03-15 at 7 05 34 PM](https://user-images.githubusercontent.com/30539832/225491084-dd1460b5-fe1d-4ae1-bf4d-fc0f01d9334f.png)
![Screen Shot 2023-03-15 at 7 05 23 PM](https://user-images.githubusercontent.com/30539832/225491132-3c730fb1-8845-4c0f-bac0-0b5c6bf21dcb.png)
