### ISSUE TITLE
FD - 002.6 - Update Mission Statement

### ISSUE THREAD

**Issue by SincerelyBrittany** [Young-N-Ambitious/yna_frontend#49]
Update Mission Statement/ Center div/ make background for entire page grey.

**Comment by Sydnee510** [comment]
-I have removed the gray background for the mission statement and have made the entire homepage background gray (not sure if they are the correct hex colors though)
this PR below addresses my background changes...
https://github.com/Young-N-Ambitious/yna_frontend/pull/53

You can still do the centering and whatever other changes needed to be made @SincerelyBrittany

**Comment by SincerelyBrittany** [comment]
Merged 👍 https://github.com/Young-N-Ambitious/yna_frontend/pull/75
