### ISSUE TITLE
FD-004.9 Add YNA Logo to Navbar

### ISSUE THREAD

**Issue by Sydnee510** [Young-N-Ambitious/yna_frontend#64]

**Comment by KiloWattDot** [comment]
So I added the yna logo to assets and I imported in the Navbar component and I placed where yall have the Link class, but I get an error for not knowing the logo image location when I start the app.
![yna logo help](https://user-images.githubusercontent.com/74320819/228039331-0d8676aa-613f-44c2-b825-cf0f5172df35.PNG)
