### ISSUE TITLE
FD-010 Create Routes for YNA Application 

### ISSUE THREAD

**Issue by lanicemp** [Young-N-Ambitious/yna_frontend#7]
**Description:**

- Create routes for YNA application

**Acceptance Criteria:**

-  routes to be created: 

  - /home  
  - /about-us 
  - /members 
  - /contact-us 
  - /join-us 
  - /login

All routes should be able to render in the DOM with a simple message letting the developer know they landed on the correct page. 

**Figma:**

- https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?node-id=156%3A12

**Comment by anujverma-eng** [comment]
Hi @lanicemp,
Greetings from India.
Can I work on this Issue?

**Comment by lanicemp** [comment]
> Hi @lanicemp, Greetings from India. Can I work on this Issue?

Yes you may! if you have any questions reach out

**Comment by Clue355** [comment]
completed
