### ISSUE TITLE
FD-003.1 Create Global Nav Bar 🌎

### ISSUE THREAD

**Issue by lanicemp** [Young-N-Ambitious/yna_frontend#8]
**Description:**

- Create the Navbar with the appropriate tabs and YNA logo.

**Acceptance** Criteria:

-  Tabs:

   -   Home | About | Members | Contact | Join

   - All links should redirect to the appropriate pages. 

   - Add testing component to check for functionality. 

**Figma:**

- https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?node-id=156%3A12

**Comment by Chaitanya-087** [comment]
i would like to work on this

**Comment by Chaitanya-087** [comment]
can you assign me this issue

**Comment by Chaitanya-087** [comment]
![image](https://user-images.githubusercontent.com/76115770/194547642-346ca521-3cda-4f9d-88ab-dd1009c59675.png)

**Comment by Clue355** [comment]
We already have this issue. Closing this duplicate one
