### ISSUE TITLE
FD-002.1 Create Home Page Asset 🏠

### ISSUE THREAD

**Issue by lanicemp** [Young-N-Ambitious/yna_frontend#9]
**Description:**

- Create the home page Asset in the Assets folder to import into the Home Page Component

**Acceptance** Criteria:

-  All pictures/Icons that will be used on the Home page.

- It will go in the global assets folder.

**Figma:**

- https://www.figma.com/file/nrf9QHTznYOpjBw8yGXD4t/YNA-Website?node-id=156%3A12

**Comment by KaifKhan7393** [comment]
@lanicemp  assign it to me so I will work on this.

**Comment by Clue355** [comment]
@KaifKhan7393 did you complete this?

**Comment by Sydnee510** [comment]
this issue can now be addressed.

**Comment by bball07** [comment]
I can take this issue

**Comment by Clue355** [comment]
you can take it if you want. it's just creating a folder @bball07

**Comment by Sydnee510** [comment]
@Clue355 you want to take this issue?
